#!/usr/bin/env bash
# ============================================================================
# tests/run.sh — test runner for SessionCinema
# ============================================================================
#
# PixInsight scripts cannot run headless from CI, so the strategy is:
#   1. strip the PixInsight preprocessor directives (#feature-id, #define
#      with line continuations) and substitute the #define tokens to obtain
#      plain JavaScript;
#   2. build tests/build/module.js: PixInsight runtime stubs + the stripped
#      script + a module.exports block exposing the pure-logic internals;
#   3. syntax-check that exact file with node --check, then run every
#      tests/*.test.js against it (stretch math, header parsing, render
#      cadence, geometry, ffmpeg command, overlays, i18n — everything that
#      does not need the PixInsight runtime).
#
# The GUI and image I/O layers are exercised in PixInsight, including the
# SESSIONCINEMA_AUTORUN headless hook (see PJSR-NOTES.md §4 and §8).
#
# Usage: tests/run.sh
# ============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="$ROOT/tests/build"
JS="$ROOT/pjsr/SessionCinema.js"
MODULE="$BUILD/module.js"

mkdir -p "$BUILD"

# #define values (same extraction as scripts/build-update-package.sh)
VERSION="$(sed -n '/^#define[[:space:]]\{1,\}SC_VERSION[[:space:]]/{ s/^#define[[:space:]]\{1,\}SC_VERSION[[:space:]]\{1,\}"\([^"]*\)".*/\1/p; q; }' "$JS")"
TITLE="$(sed -n '/^#define[[:space:]]\{1,\}SC_TITLE[[:space:]]/{ s/^#define[[:space:]]\{1,\}SC_TITLE[[:space:]]\{1,\}"\([^"]*\)".*/\1/p; q; }' "$JS")"
if [ -z "$VERSION" ] || [ -z "$TITLE" ]; then
   echo "ERROR: could not read #define SC_VERSION/SC_TITLE from $JS" >&2
   exit 1
fi

{
   # PixInsight runtime stubs needed at load time (the dialog class extends
   # Dialog at the top level; everything else is only referenced at run time)
   echo '// Generated by tests/run.sh — do not edit'
   echo 'global.Dialog = class {};'

   # Strip the preprocessor directives (including multi-line continuations),
   # substitute the #define tokens, drop the main() invocation
   awk '{ sub(/\r$/,"") } cont { cont = /\\$/; next } /^#/ { cont = /\\$/; next } { print }' "$JS" \
      | sed -e "s|\\bSC_VERSION\\b|\"$VERSION\"|g" \
            -e "s|\\bSC_TITLE\\b|\"$TITLE\"|g" \
            -e "s|\\bSESSIONCINEMA_BUILD\\b|\"dev\"|g" \
            -e 's|#__FILE__|"__FILE__"|g' \
            -e '/^main();$/d'

   # Expose the internals under test
   cat <<'EOF'

module.exports = {
   STYLE_TIMELAPSE: STYLE_TIMELAPSE,
   STYLE_STACKING: STYLE_STACKING,
   STRETCH_REF_FINAL: STRETCH_REF_FINAL,
   STRETCH_REF_FIRST: STRETCH_REF_FIRST,
   STRETCH_REF_EACH: STRETCH_REF_EACH,
   FIT_CROP: FIT_CROP,
   FIT_LETTERBOX: FIT_LETTERBOX,
   OUTPUT_FORMATS: OUTPUT_FORMATS,
   CRF_CHOICES: CRF_CHOICES,
   DEFAULT_CONFIG: DEFAULT_CONFIG,
   STRINGS: STRINGS,
   tr: tr,
   setLanguage: function (lang) { gLanguage = lang; },
   clamp01: clamp01,
   mtf: mtf,
   computeAutoStretch: computeAutoStretch,
   parseDateObs: parseDateObs,
   kwValue: kwValue,
   frameMetaFromKeywords: frameMetaFromKeywords,
   sortFrames: sortFrames,
   dominantObject: dominantObject,
   resolveTitle: resolveTitle,
   computeRenderIndices: computeRenderIndices,
   computeCoverRect: computeCoverRect,
   formatDuration: formatDuration,
   formatSnrGainDb: formatSnrGainDb,
   formatClockUT: formatClockUT,
   slugify: slugify,
   buildOverlayInfo: buildOverlayInfo,
   buildFfmpegArgs: buildFfmpegArgs,
   shellQuote: shellQuote,
   buildEncodeScriptText: buildEncodeScriptText,
   frameFileName: frameFileName,
   angularSepDeg: angularSepDeg,
   makeWcs: makeWcs,
   wcsPixelToSky: wcsPixelToSky,
   wcsImageFraming: wcsImageFraming,
   makeCamera: makeCamera,
   projectToScreen: projectToScreen,
   zoomCameraAt: zoomCameraAt,
   revealAlpha: revealAlpha,
   constellationAlpha: constellationAlpha,
   constellationLabelAlpha: constellationLabelAlpha,
   fadeBand: fadeBand,
   makeSurveyWcs: makeSurveyWcs,
   scaleWcsToDims: scaleWcsToDims,
   cropWcs: cropWcs,
   constellationCentroids: constellationCentroids,
   hips2fitsUrl: hips2fitsUrl,
   limitingMagnitude: limitingMagnitude,
   starRadius: starRadius,
   niceAngle: niceAngle,
   formatAngle: formatAngle,
   scaleBar: scaleBar,
   parseStarCatalog: parseStarCatalog,
   parseConstellationLines: parseConstellationLines,
   smoothstep01: smoothstep01
};
EOF
} > "$MODULE"

# The substitution must leave no bare token behind. This catches a
# non-GNU sed (\b word boundaries silently no-op on BSD/macOS) as well
# as a drift in the #define format — either would otherwise surface as
# opaque ReferenceErrors, or worse, pass unnoticed.
if grep -q -w -e SC_VERSION -e SC_TITLE -e SESSIONCINEMA_BUILD "$MODULE"; then
   echo "ERROR: #define token substitution failed (GNU sed required)" >&2
   exit 1
fi

# Check the exact file the tests load (script body AND exports block)
node --check "$MODULE"
echo "OK   syntax (node --check)"

failures=0
for t in "$ROOT"/tests/*.test.js; do
   if node "$t" > "$BUILD/last.log" 2>&1; then
      echo "OK   $(basename "$t")"
   else
      echo "FAIL $(basename "$t")"
      cat "$BUILD/last.log"
      failures=1
   fi
done

if [ "$failures" -ne 0 ]; then
   echo "Tests failed." >&2
   exit 1
fi
echo "All tests passed."
